version: "2.17"

services:
  pdf_reader:
    runtime: nvidia
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    tty: true
    stdin_open: true
    ports:
      - target: 8501
        published: 8501
    volumes:
        - ./:/workspace
        - /etc/localtime:/etc/localtime:ro
    working_dir: /workspace
    networks:
      - api

networks:
  api:
    name: api
    driver: bridge
